### ISSUE TITLE
Could not get class storage for eloquent

### ISSUE THREAD

**Issue by juriem-paxful** [psalm/psalm-plugin-laravel#91]
**Describe the bug**
When I try to execute psalm receiving next error

In ClassLikeStorageProvider.php line 45:
                                            
  Could not get class storage for eloquent 

**Impacted Versions**
barryvdh/laravel-debugbar             v3.3.3             PHP Debugbar integ...
barryvdh/laravel-ide-helper           v2.7.0             Laravel IDE Helper...
barryvdh/laravel-snappy               v0.4.7             Snappy PDF/Image f...
bugsnag/bugsnag-laravel               v2.17.1            Official Bugsnag n...
fruitcake/laravel-cors                v0.11.4            Adds CORS (Cross-O...
laravel/browser-kit-testing           v5.1.3             Provides backwards...
laravel/framework                     v5.8.38            The Laravel Framew...
laravel/passport                      v7.5.1             Laravel Passport p...
laravel/slack-notification-channel    v2.0.2             Slack Notification...
laravel/socialite                     v4.3.2             Laravel wrapper ar...
laravel/telescope                     v2.1.7             An elegant debug a...
laravel/tinker                        v1.0.10            Powerful REPL for ...
laravelcollective/html                v5.8.1             HTML and Form Buil...
m50/psalm-json-to-junit               dev-master 840343b Converts psalm's j...
psalm/plugin-laravel                  v1.3.0             A Laravel plugin f...
spatie/laravel-webhook-server         1.4.0              Send webhooks in L...
vimeo/psalm                           3.12.2             A static analysis ...

**Additional context**
[2020-07-07 10:58:08] local.ERROR: Could not get class storage for eloquent ["[object] (InvalidArgumentException(code: 0): Could not get class storage for eloquent at /app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45)\n[stacktrace]\n#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(93): Psalm\\Internal\\Provider\\ClassLikeStorageProvider->get('Eloquent')\n#1 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(151): Psalm\\Internal\\Analyzer\\Statements\\Expression\\Call\\StaticCallAnalyzer::analyze(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Expr\\StaticCall), Object(Psalm\\Context))\n#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\\Internal\\Analyzer\\Statements\\ExpressionAnalyzer::handleExpression(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Expr\\StaticCall), Object(Psalm\\Context), false, NULL, false)\n#3 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(246): Psalm\\Internal\\Analyzer\\Statements\\ExpressionAnalyzer::analyze(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Expr\\StaticCall), Object(Psalm\\Context))\n#4 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(128): Psalm\\Internal\\Analyzer\\Statements\\Expression\\AssignmentAnalyzer::analyze(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Expr\\Variable), Object(PhpParser\\Node\\Expr\\StaticCall), NULL, Object(Psalm\\Context), NULL)\n#5 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\\Internal\\Analyzer\\Statements\\ExpressionAnalyzer::handleExpression(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Expr\\Assign), Object(Psalm\\Context), false, NULL, true)\n#6 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(439): Psalm\\Internal\\Analyzer\\Statements\\ExpressionAnalyzer::analyze(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Expr\\Assign), Object(Psalm\\Context), false, NULL, true)\n#7 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(163): Psalm\\Internal\\Analyzer\\StatementsAnalyzer::analyzeStatement(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Stmt\\Expression), Object(Psalm\\Context), NULL)\n#8 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(795): Psalm\\Internal\\Analyzer\\StatementsAnalyzer->analyze(Array, Object(Psalm\\Context))\n#9 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(348): Psalm\\Internal\\Analyzer\\Statements\\Block\\IfAnalyzer::analyzeIfBlock(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Stmt\\If_), Object(Psalm\\Internal\\Scope\\IfScope), Object(Psalm\\Context), Object(Psalm\\Context), Object(Psalm\\Context), Array)\n#10 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(387): Psalm\\Internal\\Analyzer\\Statements\\Block\\IfAnalyzer::analyze(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Stmt\\If_), Object(Psalm\\Context))\n#11 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(163): Psalm\\Internal\\Analyzer\\StatementsAnalyzer::analyzeStatement(Object(Psalm\\Internal\\Analyzer\\StatementsAnalyzer), Object(PhpParser\\Node\\Stmt\\If_), Object(Psalm\\Context), Object(Psalm\\Context))\n#12 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(547): Psalm\\Internal\\Analyzer\\StatementsAnalyzer->analyze(Array, Object(Psalm\\Context), Object(Psalm\\Context), true)\n#13 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1803): Psalm\\Internal\\Analyzer\\FunctionLikeAnalyzer->analyze(Object(Psalm\\Context), Object(Psalm\\Internal\\Provider\\NodeDataProvider), Object(Psalm\\Context))\n#14 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(754): Psalm\\Internal\\Analyzer\\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\\Node\\Stmt\\ClassMethod), Object(Psalm\\Storage\\ClassLikeStorage), Object(Psalm\\Internal\\Analyzer\\ClassAnalyzer), Object(Psalm\\Context), Object(Psalm\\Context))\n#15 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(217): Psalm\\Internal\\Analyzer\\ClassAnalyzer->analyze(Object(Psalm\\Context), Object(Psalm\\Context))\n#16 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\\Internal\\Analyzer\\FileAnalyzer->analyze(NULL)\n#17 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(576): Psalm\\Internal\\Codebase\\Analyzer->Psalm\\Internal\\Codebase\\{closure}(2, '/app/app/Models...')\n#18 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(266): Psalm\\Internal\\Codebase\\Analyzer->doAnalysis(Object(Psalm\\Internal\\Analyzer\\ProjectAnalyzer), 1)\n#19 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1203): Psalm\\Internal\\Codebase\\Analyzer->analyzeFiles(Object(Psalm\\Internal\\Analyzer\\ProjectAnalyzer), 1, false, false)\n#20 /app/vendor/vimeo/psalm/src/psalm.php(604): Psalm\\Internal\\Analyzer\\ProjectAnalyzer->checkPaths(Array)\n#21 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')\n#22 {main}\n"]

**Comment by mr-feek** [comment]
Hrm, I wonder if this was a regression in psalm.

This was a previous report, which was fixed: https://github.com/psalm/psalm-plugin-laravel/issues/72

@juriem-paxful could you share the snippet of code that is causing the error? `./vendor/bin/psalm --debug-by-line` should help narrow it down to the file

**Comment by juriem-paxful** [comment]
`

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Affiliate
 *
 * @property integer $id
 * @property integer $user_account_id
 *
 * @property UserAccount $userAccount
 */
class Vendor extends AbstractModel
{

    use SoftDeletes;

    const DEFAULT_REFERRAL_FEE_PERCENTAGE = 20;

    protected $table = 'vendors';

    protected $dates = ['deleted_at'];

    protected $fillable = ['user_account_id', 'referral_fee_percentage'];

    public static function boot()
    {
30:        parent::boot();

        static::creating(function ($user) {
            if (empty($user->referral_fee_percentage)) {
                $user->referral_fee_percentage = self::DEFAULT_REFERRAL_FEE_PERCENTAGE;
            }
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function userAccount()
    {
        return $this->belongsTo(UserAccount::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function languages()
    {
        if (!isset($this->relations['languages'])) {
            $languages = Language::leftJoin('user_languages', 'language_code', '=', 'code')
                ->where('user_account_id', $this->user_account_id)
                ->get();
            if ($languages->count()) {
                $this->relations['languages'] = $languages->all();
            } else {
                $this->relations['languages'] = [];
            }
        }

        return $this->relations['languages'];
    }
}'

/app/app/Models/Vendor.php:30

AbstractModel extends Model

Got another error when trying to run psalm on whole project 

PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in /app/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php on line 568

**Comment by mr-feek** [comment]
Just taking note that it seems something to do with 

```php
static::creating(function ($user) {
            if (empty($user->referral_fee_percentage)) {
                $user->referral_fee_percentage = self::DEFAULT_REFERRAL_FEE_PERCENTAGE;
            }
        });
```

Perhaps we have issues  with the creating event, I will try to reproduce it in the test suite.

**Comment by mr-feek** [comment]
I'm no longer able to reproduce this, I'm going to close this as resolved.
